steps:
  #Step 1: Install dependencies
  - name: 'gcr.io/cloud-builders/npm'
    args: ['install']

  #Step 2: Deploy an App Engine
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'gcloud'
    args: 
      - 'app'
      - 'deploy'
      - 'app.yaml'
      - '--version'
      - '-v1'
      - '--quiet'